# Generated by Django 6.0 on 2025-12-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='amount',
        ),
        migrations.AddField(
            model_name='debt',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dollar qismi'),
        ),
        migrations.AddField(
            model_name='debt',
            name='amount_uzs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name="So'm qismi"),
        ),
    ]
