# Generated by Django 6.0 on 2025-12-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_debt_amount_debt_amount_usd_debt_amount_uzs'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='transaction_type',
            field=models.CharField(choices=[('debt', 'Nasiya (Qarz)'), ('payment', "To'lov (Qaytarish)")], default='debt', max_length=10),
        ),
    ]
