# Generated by Django 6.0 on 2025-12-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_debt_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_rate', models.DecimalField(decimal_places=2, default=12800, max_digits=10, verbose_name='Dollar kursi')),
            ],
        ),
    ]
