# Generated by Django 6.0 on 2025-12-13 04:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='invite_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
